name: create-model

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  
jobs:
  build-model:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: python3 -m ipykernel install --user
    # cleans output for later upload only new created tflites.
    - run: rm output/*.*
    - name: Execute
      run: |
        mkdir -p output/tmp
        jupyter nbconvert --execute --to html dig-class100-s2.ipynb --output-dir output/
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: notebook-results
        path: |
          output/*
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: tflite-model
        path: output/*.tflite
     
